name: flutter_shopware
description: Shopware plugin for Flutter.
version: 0.0.1
homepage: https://github.com/hypnotic/flutter-shopware

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.8
  flutter_lints: ^1.0.0
  json_serializable: ^6.1.5
